spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    servlet:
      content-type: text/html
    mode: HTML
  datasource:
    url: jdbc:mysql://1.116.78.177:3306/miaosha?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    data-password: 123456
    data-username: root
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true

  redis:
    sentinel:
      master: mymaster
      nodes: 42.192.147.225:26379
      password: lihaonan1
    database: 0 # 数据库索引，默认0
    connect-timeout: 1800000 #超时事件
    lettuce:
        pool:
          max-active: 20
          max-wait: -1
          max-idle: 5
          min-idle: 1
    password: lihaonan1

  aop:
    auto: true
    proxy-target-class: true

mybatis:
  type-aliases-package: com.lhn.domain
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
